language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run build -- --prod --base-href https://taljacobson.github.io/mdgo-test/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/mdgo-test
  on:
    branch: master